### ISSUE TITLE
Concatenate multiple EventHandlers in one config

### ISSUE THREAD

**Issue by mrvanes** [SURFscz/SRAMsync#10]
It would be nice to be able to independantly configure multiple EventHandlers in one config. The advantages would be:

1. Simpler cua/cba dependancy (serial instead of implied)
2. Use of yaml anchors for EventHandlers that share config (cua/cba)
3. No more use of `auxiliary_event_handler`

**Comment by venekamp** [comment]
Done in commit e2d3fcfad91f100fe48a594bd0c722d6a6c183f2
