### ISSUE TITLE
Mutables are called by reference

### ISSUE THREAD

**Issue by mrvanes** [SURFscz/SRAMsync#17]
https://github.com/SURFscz/SRAMsync/blob/b9f2904276a22884027a90c9c0f99652ab6bcd44/SRAMsync/sync_with_sram.py#L372
These lines could be simply replaced by
```
        process_user_data(cfg, fq_co, co, status, new_status)
        process_group_data(cfg, fq_co, org, co, status, new_status)
```
Since new_status is called by reference and modified by the called function. This happens to all mutable objects in python.

Same here:
https://github.com/SURFscz/SRAMsync/blob/b9f2904276a22884027a90c9c0f99652ab6bcd44/SRAMsync/sync_with_sram.py#L482-L484

And here:
https://github.com/SURFscz/SRAMsync/blob/b9f2904276a22884027a90c9c0f99652ab6bcd44/SRAMsync/sync_with_sram.py#L599-L600

**Comment by venekamp** [comment]
Assignments have been removed.
