### ISSUE TITLE
Code review SRAMsync

### ISSUE THREAD

**Issue by venekamp** [SURFscz/SRAMsync#2]
Please review v3.3.1 or later.

**Comment by baszoetekouw** [comment]
@venekamp @mrvanes Wat is hier de status van?

**Comment by mrvanes** [comment]
Ik heb wat issues en PR's aangemaakt waarvan Gerben een groot deel verwerkt heeft:
https://github.com/SURFscz/SRAMsync/issues?q=is%3Aissue+is%3Aclosed
https://github.com/SURFscz/SRAMsync/pulls?q=is%3Apr+author%3Amrvanes+is%3Aclosed+

**Comment by mrvanes** [comment]
Deze issues staan nog open, maar ik weet niet of Gerben die nog op gaat pakken. Sommige waren losse flodders die het overwegen waard waren, maar niet heel belangrijk.
https://github.com/SURFscz/SRAMsync/issues/created_by/mrvanes

**Comment by venekamp** [comment]
Alle issues die Martin heeft zijn afgehandeld.
