### ISSUE TITLE
Documentation mentions DEBUG level for DummyEventHandler

### ISSUE THREAD

**Issue by mrvanes** [SURFscz/SRAMsync#22]
https://github.com/SURFscz/SRAMsync/blob/b9f2904276a22884027a90c9c0f99652ab6bcd44/SRAMsync/dummy_event_handler.py#L12
Documentation mentions DEBUG level for DummyEventHandler logging, but this looks like info?

**Comment by venekamp** [comment]
Should be info indeed. Fixed.
