### ISSUE TITLE
Remove group doesn't print group to be removed

### ISSUE THREAD

**Issue by mrvanes** [SURFscz/SRAMsync#24]
https://github.com/SURFscz/SRAMsync/blob/b9f2904276a22884027a90c9c0f99652ab6bcd44/SRAMsync/cua_script_generator.py#L236
It's not very helpful to not print the name of the group if there is no command or intention to remove a group?

**Comment by venekamp** [comment]
Fixed in fc403905e86a91e374d54fb2016d10dd725829f1
