### ISSUE TITLE
Unused assignment

### ISSUE THREAD

**Issue by mrvanes** [SURFscz/SRAMsync#25]
https://github.com/SURFscz/SRAMsync/blob/b9f2904276a22884027a90c9c0f99652ab6bcd44/SRAMsync/email_notifications.py#L169
_DEFAULT_CIPHERS is unused in EmailNotifications

**Comment by venekamp** [comment]
_DEFAULT_CIPHERS is used on line:

https://github.com/SURFscz/SRAMsync/blob/9f959df1b07e3093d768a924cb910d5c4c739e7a/SRAMsync/email_notifications.py#L84
