### ISSUE TITLE
Move responsibility of getting a status to EventClass implementation

### ISSUE THREAD

**Issue by venekamp** [SURFscz/SRAMsync#31]
In the current setup, the loading the status file is the responsibility of the main loop. Pushing this responsibility into EventClass derived classes, creates more flexibility. It could be a file, but in case of a more ldap-to-ldap copy it could be reading the current state of the destination ldap, instead of a json file. The EventClass should know best how to obtain the current destination state.

**Comment by FlorisFokkinga** [comment]
@venekamp, which repo is this about?

**Comment by venekamp** [comment]
Feature is implemented in commit 8ef6ebd8f56cb763d4df7116a63c6d19de531388
