### ISSUE TITLE
Unclear use of local

### ISSUE THREAD

**Issue by mrvanes** [SURFscz/SRAMsync#4]
https://github.com/SURFscz/SRAMsync/blob/b9f2904276a22884027a90c9c0f99652ab6bcd44/README.md?plain=1#L236

It is unclear from the use of the word what local means in this context, maybe replace with (or add) _source_ or _SRAM_?

**Comment by venekamp** [comment]
Service is referring to the service for which the config file is meant. Hence 'local'. I'll make it more clear.

**Comment by venekamp** [comment]
Changed to: The `service` key is for specifying the name of the service for which the configuration is created.
