### ISSUE TITLE
SMTP connection can have secrets

### ISSUE THREAD

**Issue by mrvanes** [SURFscz/SRAMsync#5]
https://github.com/SURFscz/SRAMsync/blob/b9f2904276a22884027a90c9c0f99652ab6bcd44/README.md?plain=1#L249

Not true anymore:
https://github.com/SURFscz/SRAMsync/blob/b9f2904276a22884027a90c9c0f99652ab6bcd44/README.md?plain=1#L295

**Comment by venekamp** [comment]
Text rewritten.
