### ISSUE TITLE
Merge grace_period and grace configuration

### ISSUE THREAD

**Issue by mrvanes** [SURFscz/SRAMsync#8]
https://github.com/SURFscz/SRAMsync/blob/b9f2904276a22884027a90c9c0f99652ab6bcd44/README.md?plain=1#L398

Consider removing or simplyfying `grace(_period)` configuration. If we specify `grace` section for a group, we imply `grace_period`.

This example breaks the requirements:
https://github.com/SURFscz/SRAMsync/blob/b9f2904276a22884027a90c9c0f99652ab6bcd44/README.md?plain=1#L461

**Comment by venekamp** [comment]
Fix in comit e261c97d81fb9a8060f2b4cc1012c132b5d4ea15
